# Generated by Django 3.1.7 on 2021-03-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=200)),
                ('sub_category_name', models.CharField(max_length=200)),
                ('sub_sub_category_name', models.CharField(max_length=200)),
                ('jobname', models.CharField(max_length=200)),
                ('startdate', models.DateField(max_length=200)),
                ('lastdate', models.DateField(max_length=200)),
                ('offlinedate', models.DateField(max_length=200)),
                ('applylink', models.CharField(max_length=500)),
                ('official_notification_link', models.CharField(max_length=500)),
                ('official_website_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='main_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=200)),
                ('sub_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sub_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=200)),
                ('sub_category_name', models.CharField(max_length=200)),
                ('sub_sub_category_name', models.CharField(max_length=200)),
            ],
        ),
    ]
